/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JustifiedGallery {
        "fullWidthCadence": number;
        "gutter": number;
        "justifyLastRow": boolean;
        "rebuildSensitivity": number;
        "rowHeightBandwidth": number;
        "targetRowHeight": number;
    }
}
declare global {
    interface HTMLJustifiedGalleryElement extends Components.JustifiedGallery, HTMLStencilElement {
    }
    var HTMLJustifiedGalleryElement: {
        prototype: HTMLJustifiedGalleryElement;
        new (): HTMLJustifiedGalleryElement;
    };
    interface HTMLElementTagNameMap {
        "justified-gallery": HTMLJustifiedGalleryElement;
    }
}
declare namespace LocalJSX {
    interface JustifiedGallery {
        "fullWidthCadence"?: number;
        "gutter"?: number;
        "justifyLastRow"?: boolean;
        "rebuildSensitivity"?: number;
        "rowHeightBandwidth"?: number;
        "targetRowHeight"?: number;
    }
    interface IntrinsicElements {
        "justified-gallery": JustifiedGallery;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "justified-gallery": LocalJSX.JustifiedGallery & JSXBase.HTMLAttributes<HTMLJustifiedGalleryElement>;
        }
    }
}
